name: smart_dash_home
description: "Implements Smart Dash Home feature"
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/features/smart_dash_home
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Smart Dash packages (managed by Mesos)
  smart_dash_common: any
  smart_dash_geocoder: any
  smart_dash_websocket: any
  smart_dash_datasource: any
  smart_dash_integration: any

  optional: ^6.1.0+1
  collection: ^1.18.0

  dio: ^5.4.3+1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  problem_details: ^0.0.2
  shelf_web_socket: ^2.0.1
  web_socket_channel: ^3.0.1

  riverpod: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  logging: ^1.3.0
  shelf_test_handler: ^2.0.2

  freezed: ^3.0.6
  mockito: ^5.4.4
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
#flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
