name: smart_dash_geocoder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # Smart Dash packages (managed by Mesos)
  smart_dash_common: any
  smart_dash_integration: any

  dio: ^5.4.3+1
  async: ^2.11.0
  logging: ^1.2.0
  optional: ^6.1.0+1
  collection: ^1.18.0
  mqtt_client: ^10.2.1
  universal_io: ^2.2.2
  stream_transform: ^2.1.0

  osm_nominatim: ^3.0.0

  riverpod: ^3.0.0-dev.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  test: ^1.25.8
  lints: ^3.0.0
  custom_lint: ^0.5.11

  freezed: ^2.5.7
  build_runner: ^2.4.13
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
  json_serializable: ^6.8.0