name: smart_dash
description: A custom smart home assistant for personal use
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  dio: ^5.4.1
  xml: ^6.5.0
  http: ^1.2.1
  path: ^1.9.0
  intl: ^0.18.0
  html: ^0.15.4
  universal_io: ^2.2.2
  path_provider: ^2.1.2
  window_manager: ^0.3.8

  nanoid: ^1.0.0
  logging: ^1.2.0
  strings: ^3.1.1
  timeago: ^3.6.1
  optional: ^6.1.0+1
  collection: ^1.18.0
  pretty_bytes: ^6.1.0
  stream_transform: ^2.1.0
  battery_indicator: ^0.1.2

  # Local storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  drift: ^2.16.0
  drift_dev: ^2.16.0
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.20

  fl_chart: ^0.66.2
  dashboard: ^0.0.4
  go_router: ^13.2.0
  settings_ui: ^2.0.2
  charts_painter: ^3.1.1
  reactive_forms: ^16.1.1
  cupertino_icons: ^1.0.6
  chart_sparkline: ^1.0.14
  flutter_gravatar: ^2.0.2
  flutter_json_view: ^1.1.4
  flutter_riverpod: ^3.0.0-dev.3
  flutter_wall_layout: ^2.1.1
  adaptive_breakpoints: ^0.1.7
  flutter_secure_storage: ^9.0.0

  eval_ex: ^1.1.8

  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  media_kit_libs_android_video: ^1.3.6

  mqtt_client: ^10.2.0
  network_tools: ^5.0.1

  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^3.0.0-dev.3

  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.0.0

  sentry: ^7.16.1
  sentry_flutter: ^7.16.1

  stack_trace: ^1.11.1

  restoration_web_plugin:
    path: plugins/restoration_web_plugin


dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.24.9
  custom_lint: ^0.5.11
  flutter_lints: ^3.0.1

  freezed: ^2.4.7
  build_runner: ^2.4.8
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
  json_serializable: ^6.7.1

dependency_overrides:
  dashboard:
    git:
      url: https://github.com/DISCOOS/dashboard.git
      ref: master
  chart_sparkline:
    git:
      url: https://github.com/DISCOOS/chart_sparkline.git
      ref: master
#  network_tools:
#    path: ../network_tools

flutter:

  # Use Material Icons fonts.
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/weather/
    - assets/images/weather/

  fonts:
    - family: SmartDashIcons
      fonts:
        - asset: fonts/SmartDashIcons.ttf
