name: smart_dash
description: A custom smart home assistant for personal use
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  dio: ^5.4.0
  xml: ^6.5.0
  http: ^1.0.0
  path: ^1.8.3
  intl: ^0.18.1
  html: ^0.15.4
  path_provider: ^2.1.1
  universal_io: ^2.2.2
  window_manager: ^0.3.7

  logging: ^1.2.0
  strings: ^3.0.0
  timeago: ^3.6.0
  optional: ^6.1.0+1
  collection: ^1.18.0
  pretty_bytes: ^6.1.0
  stream_transform: ^2.1.0
  battery_indicator: ^0.1.2
  shared_preferences: ^2.2.2

  drift: ^2.14.1
  drift_dev: ^2.14.1
  sqlite3: ^2.3.0
  sqlite3_flutter_libs: ^0.5.18

  fl_chart: ^0.66.0
  dashboard: ^0.0.4
  go_router: ^13.0.0
  settings_ui: ^2.0.2
  charts_painter: ^3.1.1
  reactive_forms: ^16.1.1
  cupertino_icons: ^1.0.6
  chart_sparkline: ^1.0.14
  flutter_gravatar: ^2.0.2
  flutter_json_view: ^1.1.4
  flutter_riverpod: ^3.0.0-dev.3
  flutter_wall_layout: ^2.1.1
  adaptive_breakpoints: ^0.1.7
  flutter_secure_storage: ^9.0.0

  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  media_kit_libs_android_video: ^1.3.6

  mqtt_client: ^10.2.0
  network_tools_flutter: ^1.0.5

  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^3.0.0-dev.3

  sentry: ^7.14.0
  sentry_flutter: ^7.14.0

  stack_trace: ^1.11.1

  restoration_web_plugin:
    path: plugins/restoration_web_plugin


dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.24.9
  custom_lint: ^0.5.7
  flutter_lints: ^3.0.1

  freezed: ^2.4.6
  build_runner: ^2.4.7
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
  json_serializable: ^6.7.1

dependency_overrides:
  dashboard:
    git:
      url: https://github.com/DISCOOS/dashboard.git
      ref: master
  chart_sparkline:
    git:
      url: https://github.com/DISCOOS/chart_sparkline.git
      ref: master
  network_tools:
    path: ../network_tools

flutter:

  # Use Material Icons fonts.
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/weather/
    - assets/images/weather/

