name: smart_dash_common
description: A SmartDash package with common functionality
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/packages/smart_dash_common
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # FLUTTER
  internet_connection_checker_plus: ^2.5.2

  # DART
  dio: ^5.7.0
  path: ^1.9.0
  compute: ^1.0.2
  optional: ^6.1.0+1

  shelf: ^1.4.1
  shelf_router: ^1.1.4
  problem_details: ^0.0.2

  hive: ^2.2.3
  sentry: ^8.9.0
  logging: ^1.3.0
  app_dirs: ^0.2.0
  universal_io: ^2.2.2
  path_provider: ^2.1.5
  xdg_directories: ^1.1.0

  riverpod: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8

  freezed: ^3.0.6
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
