name: smart_dash_notification
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # Smart Dash packages (managed by Mesos)
  smart_dash_common: ^1.0.0

  logging: ^1.3.0

  hive: ^2.2.3
  optional: ^6.1.0+1
  universal_io: ^2.2.2
  hive_flutter: ^1.1.0

  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.0

  riverpod: ^3.0.0-dev.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8

  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
