name: restoration_web_plugin
description: A web platform plugin that implements missing state restoration support in flutter
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  plugin_platform_interface: ^2.1.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: RestorationWebPlugin
        fileName: restoration_web_plugin.dart
