name: restoration_web_plugin
description: A web platform plugin that implements missing state restoration support in flutter
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/packages/restoration_web_plugin
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  plugin_platform_interface: ^2.1.8
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: RestorationWebPlugin
        fileName: restoration_web_plugin.dart
