name: smart_dash_datasource
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:

  path: ^1.9.0
  path_provider: ^2.1.5

  sentry: ^8.9.0
  logging: ^1.3.0

  drift: ^2.21.0
  drift_dev: ^2.21.2
  sqlite3: ^2.4.7
  sqlite3_flutter_libs: ^0.5.26

  riverpod: 3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8

  build_runner: ^2.4.13
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
