name: smart_dash_datasource
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/packages/smart_dash_datasource
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # Smart Dash packages (managed by Mesos)
  smart_dash_common: any
  smart_dash_websocket: any

  # FLUTTER
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  internet_connection_checker_plus: ^2.5.2

  path: ^1.9.0
  optional: ^6.1.0+1
  collection: ^1.18.0
  path_provider: ^2.1.5

  dio: ^5.4.3+1
  hive: ^2.2.3
  universal_io: ^2.2.2

  sentry: ^8.9.0
  logging: ^1.3.0

  drift: ^2.21.0
  drift_dev: ^2.21.2
  sqlite3: ^2.4.7
  sqlite3_flutter_libs: ^0.5.26

  riverpod: 3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8

  freezed: ^2.5.7
  build_runner: ^2.4.13
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
  json_serializable: ^6.8.0
