name: smart_dash_datasource
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/packages/smart_dash_datasource
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # Smart Dash packages (managed by Mesos)
  smart_dash_common: any
  smart_dash_websocket: any

  # FLUTTER
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3
  shared_preferences_android: ^2.4.0
  flutter_secure_storage: ^9.2.2
  internet_connection_checker_plus: ^2.5.2

  path: ^1.9.0
  optional: ^6.1.0+1
  collection: ^1.18.0
  path_provider: ^2.1.5

  dio: ^5.8.0+1
  hive: ^2.2.3
  shelf: ^1.4.1
  async: ^2.11.0
  crypto: ^3.0.6
  universal_io: ^2.2.2
  shelf_router: ^1.1.4
  problem_details: ^0.0.2
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.1
  dio_cache_interceptor: ^4.0.3

  sentry: ^8.9.0
  logging: ^1.3.0

  drift: ^2.21.0
  drift_dev: ^2.21.2
  sqlite3: ^2.4.7
  sqlite3_flutter_libs: ^0.5.26

  riverpod: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8

  freezed: ^3.0.6
  mockito: ^5.4.5
  build_runner: ^2.4.13
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  json_serializable: ^6.8.0
