name: smart_dash_cloud
description: A SmartDash server app for cloud functionality.
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/backends/smart_dash_cloud
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

  # Smart Dash packages (managed by Mesos)
  smart_dash_account: any

  nanoid: ^1.0.0
  optional: ^6.1.0+1
  logging: ^1.3.0


  args: ^2.6.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  problem_details: ^0.0.2

  riverpod: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  http: ^1.3.0

  test: ^1.25.8
  lints: ^5.1.1

  freezed: ^3.0.6
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
