name: smart_dash_cloud
description: A SmartDash server app for cloud functionality.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

  # Smart Dash packages (managed by Mesos)
  smart_dash_account: any

  nanoid: ^1.0.0
  optional: ^6.1.0+1
  logging: ^1.2.0


  args: ^2.6.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  problem_details: ^0.0.2

  riverpod: ^3.0.0-dev.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  http: ^1.2.2

  test: ^1.25.8
  lints: ^3.0.0
  custom_lint: ^0.5.11

  freezed: ^2.5.7
  build_runner: ^2.4.13
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
  json_serializable: ^6.8.0

dependency_overrides:
  analyzer: 6.7.0
