name: smart_dash_gateway
description: A server app using the shelf package and Docker.
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/backends/smart_dash_gateway
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # Smart Dash packages (managed by Mesos)
  smart_dash_common: any

  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^5.1.1
  test: ^1.25.8
