/// Flutter icons SmartDashIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SmartDashIcons
///      fonts:
///       - asset: fonts/SmartDashIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SmartDashIcons {
  SmartDashIcons._();

  static const _kFontFam = 'SmartDashIcons';
  static const String? _kFontPkg = null;

  static const IconData parameter = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData function = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData variable = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData process = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData process_outlined = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_outlined = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
