name: smart_dash_daemon
description: A Smart Dash daemon service for integrations with devices
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.6.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  http: ^1.2.2
  lints: ^3.0.0
  test: ^1.25.8
