name: smart_dash_account
description: Provides core functionality for managing user identities, profiles, and configurations.
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/features/smart_dash_account
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:

  flutter:
    sdk: flutter

  # Smart Dash packages (managed by Mesos)
  smart_dash_home: any
  smart_dash_common: any
  smart_dash_geocoder: any
  smart_dash_datasource: any
  smart_dash_integration: any

  dio: ^5.8.0+1
  shelf: ^1.4.2
  shelf_router: ^1.1.4

  async: ^2.12.0
  nanoid: ^1.0.0
  logging: ^1.3.0
  optional: ^6.1.0+1

  drift: ^2.26.0
  drift_dev: ^2.26.0
  drift_flutter: ^0.2.4
  sqlite3: ^2.7.5
  sqlite3_flutter_libs: ^0.5.32

  riverpod: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  freezed: ^3.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  json_serializable: ^6.8.0
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
