name: smart_dash_weather
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # Smart Dash packages (managed by Mesos)
  smart_dash_flow: any
  smart_dash_common: any
  smart_dash_device: any
  smart_dash_geocoder: any
  smart_dash_datasource: any
  smart_dash_integration: any

  intl: ^0.19.0
  path: ^1.9.0
  async: ^2.11.0
  logging: ^1.2.0
  optional: ^6.1.0+1
  collection: ^1.18.0
  universal_io: ^2.2.2

  dio: ^5.4.3+1
  eval_ex: ^1.1.8

  stream_transform: ^2.1.0

  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  media_kit_libs_android_video: ^1.3.6

  riverpod: ^3.0.0-dev.3

  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^3.0.0-dev.3


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8

  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11