name: smart_dash_websocket
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/packages/smart_dash_websocket
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:

  # Smart Dash packages (managed by Mesos)
  smart_dash_common: any

  logging: ^1.2.0

  shelf: ^1.4.1
  shelf_web_socket: ^2.0.1
  web_socket_channel: ^3.0.1

  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  test: ^1.25.8
  lints: ^3.0.0
  custom_lint: ^0.5.11

  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0