name: smart_dash_presence
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/features/smart_dash_presence
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # Smart Dash packages (managed by Mesos)
  smart_dash_flow: any
  smart_dash_common: any
  smart_dash_account: any
  smart_dash_datasource: any

  path: ^1.9.0
  intl: ^0.19.0
  async: ^2.11.0
  strings: ^3.1.1
  logging: ^1.2.0
  optional: ^6.1.0+1
  collection: ^1.18.0
  universal_io: ^2.2.2
  network_tools: ^5.0.2

  stream_transform: ^2.1.0

  riverpod: ^3.0.0-dev.3

  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^3.0.0-dev.3


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8

  freezed: ^2.5.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
