name: smart_dash_snow
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/features/smart_dash_snow
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # Smart Dash packages (managed by Mesos)
  smart_dash_common: any
  smart_dash_device: any
  smart_dash_datasource: any
  smart_dash_integration: any


  path: ^1.9.0
  intl: ^0.19.0
  html: ^0.15.4
  async: ^2.11.0
  logging: ^1.2.0
  optional: ^6.1.0+1
  universal_io: ^2.2.2

  dio: ^5.4.3+1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  stream_transform: ^2.1.0
  dio_cache_interceptor: ^3.5.1

  sentry: ^8.0.0
  sentry_flutter: ^8.0.0

  riverpod: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8

  freezed: ^3.0.6
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
