name: smart_dash_integration
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/kengu/no.kengu.smart_dash.git/packages/smart_dash_integration
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:

  # Smart Dash packages (managed by Mesos)
  smart_dash_common: any
  smart_dash_websocket: any
  smart_dash_datasource: any

  async: ^2.11.0
  strings: ^3.1.1
  logging: ^1.2.0
  optional: ^6.1.0+1
  collection: ^1.18.0
  universal_io: ^2.2.2
  stream_transform: ^2.1.0

  dio: ^5.4.3+1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  problem_details: ^0.0.2

  riverpod: ^3.0.0-dev.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  test: ^1.25.8
  lints: ^3.0.0
  custom_lint: ^0.5.11
  shelf_test_handler: ^2.0.2

  freezed: ^2.5.7
  mockito: ^5.4.4
  build_runner: ^2.4.13
  riverpod_lint: ^3.0.0-dev.4
  riverpod_generator: ^3.0.0-dev.11
  json_serializable: ^6.8.0