name: Publish

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags: '[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches: [ "main" ]

jobs:
#  compile:
#    name: Compile Backends
#    strategy:
#      matrix:
#        include:
#          - runs-on: ubuntu-latest
#            binary-name: linux_amd64
#          - runs-on: macos-latest
#            binary-name: macos_amd64
#          - runs-on: windows-latest
#            binary-name: windows.exe
#    runs-on: ${{ matrix.runs-on }}
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Setup Flutter
#        uses: flutter-actions/setup-flutter@v3
#        with:
#          channel: stable
#          version: latest
#
#      - name: Setup melos
#        uses: bluefireteam/melos-action@v3
#
#      - name: Create Build Folder
#        run: mkdir -p build/${{ matrix.runs-on }}
#
#      - name: Build Cloud Backend
#        run: dart compile exe ./backends/smart_dash_cloud/bin/main.dart -o build/${{ matrix.runs-on }}/cloud_${{ matrix.binary-name }}
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: bin-${{ matrix.runs-on }}
#          path: build/${{ matrix.runs-on }}


  compile-rpi:
    name: Compile Backends for RPI
    runs-on: [self-hosted, sjokoladehuset, arm64, rpi4b]
    steps:
      - uses: actions/checkout@v3

      - name: Setup melos
        uses: bluefireteam/melos-action@v3

      - name: Create Build Folder
        run: mkdir -p build/rpi4b-arm64

      - name: Build Cloud Backend
        run: dart compile exe ./backends/smart_dash_cloud/bin/main.dart -o build/rpi4b-arm64/cloud_rpi4b_arm64

      - uses: actions/upload-artifact@v3
        with:
          name: bin-rpi4b-arm64
          path: build/rpi4b-arm64


  release:
    needs:
#      - compile
      - compile-rpi
    name: Github Release
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/download-artifact@v3
#        with:
#          name: bin-ubuntu-latest
#          path: bin-linux
#      - uses: actions/download-artifact@v3
#        with:
#          name: bin-macos-latest
#          path: bin-macos
#      - uses: actions/download-artifact@v3
#        with:
#          name: bin-windows-latest
#          path: bin-windows
      - uses: actions/download-artifact@v3
        with:
          name: bin-rpi4b-arm64
          path: bin-rpi4b-arm64
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: bin-*/*
      - name: Post release details
        if: success()
        run: echo "Release draft created successfully."
